name: sqlc_gen_dart_example
description: dexample
version: 1.0.0
repository: https://github.com/ryota0624/sqlc-gen-dart
publish_to: none
environment:
  sdk: ^3.4.3

dependencies:
  postgres: ^3.4.4
  duckdb_dart: ^0.3.6
  sqlc_dart: ^0.0.0
  sqlc_postgres_dart: 0.0.0
  sqlc_duckdb_dart: 0.0.0
  sqlc_sqlite3_dart: 0.0.0
  sqlite3: ^2.4.7
  fpdart: ^1.1.1
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
