name: sqlc_gen_dart_example
description: dexample
version: 1.0.0
repository: https://github.com/ryota0624/sqlc-gen-dart

environment:
  sdk: ^3.4.3

dependencies:
  postgres: ^3.4.4
  duckdb_dart: any
  sqlc_dart: any
  sqlc_postgres_dart: any
  sqlc_duckdb_dart: any
  sqlc_sqlite3_dart: any
  sqlite3: ^2.4.7
  fpdart: ^1.1.1
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
