name: sqlc_duckdb_dart
description: dart library for sqlc duckdb support
version: 0.0.0
repository: https://github.com/ryota0624/sqlc-gen-dart

environment:
  sdk: ^3.4.3

dependencies:
  duckdb_dart: ^0.3.6
  meta: ^1.16.0
  collection: ^1.15.0
  sqlc_dart: ^0.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
