name: release

on:
  workflow_dispatch:
    inputs:
      modify_readme:
        type: boolean
        default: false
        description: 'modify getting started in README.md'
        required: false
      release_name:
        type: string
        description: 'name of the release'
        required: true
  push:
    tags:
      - "v*.*.*"

jobs:
  build_wasm:
    name: build_image
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go 1.23.1
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.1
          cache-dependency-path: |
            plugin/go.sum
      - name: build wasm
        id: build
        run: |
          make build_plugin_wasm
          mv plugin/sqlc-gen-dart.wasm sqlc-gen-dart.wasm
          CHECKSUM=$(sha256sum sqlc-gen-dart.wasm | awk '{print $1}')
          echo "checksum=${CHECKSUM}" >> $GITHUB_OUTPUT
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: sqlc-gen-dart.wasm
          body: checksum=${{ steps.build.outputs.checksum }}
          tag_name: ${{ (github.event.inputs.release_name != '' && github.event.inputs.release_name) || github.ref_name }}
      - name: modify getting started
        if: ${{ github.event.inputs.modify_readme == 'true' }}
        env:
          PLUGIN_CHECKSUM: ${{ steps.build.outputs.checksum }}
        run: |
          git checkout -b main
          TAG=${GITHUB_REF#refs/*/}
          DOWNLOAD_URL="https://github.com/ryota0624/buf-sandbox/releases/download/${TAG}/sqlc-gen-dart.wasm"
          DOWNLOAD_URL_LINE="      url: ${DOWNLOAD_URL}"
          CHECKSUM_LINE='      sha256: "'${PLUGIN_CHECKSUM}'"'
          awk -v replaceLine="${DOWNLOAD_URL_LINE}" '
          {
            if ($0 ~ "url: https://github.com/ryota0624/sqlc-gen-dart/releases/download")
              print replaceLine;
              else
              print;
          }' README.md > README.tmp && mv README.tmp README.md
          
          awk -v replaceLine="${CHECKSUM_LINE}" '
          {
            if ($0 ~ "sha256:")
            print replaceLine;
            else
            print;
          }' README.md > README.tmp && mv README.tmp README.md
          git push --set-upstream origin main
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "Update README.md"
          git push
